// flow-typed signature: 52c45d5160da50fd52990b8850e3e117
// flow-typed version: <<STUB>>/@types/react-relay_v^14.1.1/flow_v0.187.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-relay' {
  declare module.exports: any;
}
