// flow-typed signature: 48fa1a3f2444668a86b9911a4526f1d3
// flow-typed version: <<STUB>>/relay-compiler_v^14.1.0/flow_v0.187.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-compiler/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-compiler/cli.js' {
  declare module.exports: $Exports<'relay-compiler/cli'>;
}
declare module 'relay-compiler/index' {
  declare module.exports: $Exports<'relay-compiler'>;
}
declare module 'relay-compiler/index.js' {
  declare module.exports: $Exports<'relay-compiler'>;
}
